# Generated by Django 6.0.5 on 2026-05-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_sortiestock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortieStock',
            new_name='SortiStock',
        ),
    ]
